log_level: INFO

storage:
  storage_path: /qdrant/storage
  snapshots_path: /qdrant/snapshots

  on_disk_payload: true

  wal:
    wal_capacity_mb: 2048
    wal_segments_ahead: 2

  optimizers:
    deleted_threshold: 0.2
    vacuum_min_vector_number: 1000
    default_segment_number: 4
    max_segment_size_kb: null
    indexing_threshold_kb: 1000
    flush_interval_sec: 5
    max_optimization_threads: 2

  hnsw_index:
    m: 32
    ef_construct: 256
    full_scan_threshold_kb: 1000
    max_indexing_threads: 2
    on_disk: false

  performance:
    max_search_threads: 0          # 0 = авто
    optimizer_cpu_budget: 2
    update_rate_limit: null

service:
  host: "0.0.0.0"
  http_port: 6333
  grpc_port: 6334

  max_request_size_mb: 64
  max_workers: 0

  enable_cors: true
  enable_tls: false

  api_key: null
  read_only_api_key: null

telemetry_disabled: true

cluster:
  enabled: false   # включишь, когда будет несколько нод

metrics:
  enabled: true
  bind_address: "0.0.0.0:9090"